export const REQUEST_POKEMONS = 'REQUEST_POKEMONS';
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const SORT_POKEMONS_BY = 'SORT_POKEMONS_BY';
export const SORT_POKEMONS_BY_WEAKNESS = 'SORT_POKEMONS_BY_WEAKNESS';
export const FIND_CURRENT_POKEMON_BY_NUM = 'FIND_CURRENT_POKEMON_BY_NUM';
export const RESET_CURRENT_POKEMON = 'RESET_CURRENT_POKEMON';
